### ISSUE TITLE
IN_ADDR lacks a "using" field

### ISSUE THREAD

**Issue by disarray2077** [jayrulez/Win32-Beef#2]
The below line should be a "using" field since it's a union, I think there are more places with this issue but this is the one I found while trying to use the bindings.

https://github.com/jayrulez/Win32-Beef/blob/d1390de8928a3e519f2f99a14be17a977a11170f/Win32/src/Generated/Networking/WinSock.bf#L1867

**Comment by jayrulez** [comment]
I think this is consistent with the documentation here:
https://learn.microsoft.com/en-us/windows/win32/api/winsock2/ns-winsock2-in_addr

Even though _S_un_e__Union is a union, it is not anonymous so we don't want to bring the members into IN_ADDR directly.
S_un_b, S_un_w, and S_addr should be accessed via S_un.

**Comment by disarray2077** [comment]
You're right, looks like the MSVC C++ API actually uses macros under the hood

![image](https://user-images.githubusercontent.com/86157825/192183448-bf25a938-fb15-4751-bd40-ad49f6dc3584.png)

I have no idea if things like this even are in win32metadata, so I guess I will just accept it.
