### ISSUE TITLE
INADDR_ANY and INADDR_BROADCAST aren't defined anywhere

### ISSUE THREAD

**Issue by disarray2077** [jayrulez/Win32-Beef#4]
Currently `INADDR_LOOPBACK` and `INADDR_NONE` are defined, but there's no `INADDR_ANY` or `INADDR_BROADCAST` anywhere.

https://github.com/jayrulez/Win32-Beef/blob/d1390de8928a3e519f2f99a14be17a977a11170f/Win32/src/Generated/Networking/WinSock.bf#L184-L185

**Comment by jayrulez** [comment]
These aren't defined in the JSON. I added them to the manual bindings file. They are available under the same namespace as the related constants.
