### ISSUE TITLE
WSAOVERLAPPED isn't defined anywhere

### ISSUE THREAD

**Issue by disarray2077** [jayrulez/Win32-Beef#6]
The bindings seem to lack the [WSAOVERLAPPED](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/ns-winsock2-wsaoverlapped) struct.

**Comment by jayrulez** [comment]
Which APIs use this type?

According to https://learn.microsoft.com/en-us/windows/win32/api/winsock2/ns-winsock2-wsaoverlapped, the type is compatible with this one: 

https://github.com/jayrulez/Win32-Beef/blob/master/Win32/src/Generated/System/IO.bf#L12

**Comment by disarray2077** [comment]
Some APIs like [WSAGetOverlappedStatus](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsagetoverlappedresult) ask for a WSAOVERLAPPED pointer. But you're right, OVERLAPPED seems to be compatible

**Comment by jayrulez** [comment]
Yeah

```
	[Import("WS2_32.lib"), CLink, CallingConvention(.Stdcall)]
	public static extern BOOL WSAGetOverlappedResult(SOCKET s, OVERLAPPED* lpOverlapped, uint32* lpcbTransfer, BOOL fWait, uint32* lpdwFlags);
```

The function generated from the metadata even uses OVERLAPPED
