### ISSUE TITLE
Issues when running the bare exe's

### ISSUE THREAD

**Issue by wilsonk** [jayrulez/Win32-Beef#7]
When I run the XAudio sample by hand from within the Debug or Release directories, I get no sound output. Debug just quits pretty quickly with no window or anything and Release seems to hang a while, then dies before window creation.

The example plays fine in the IDE under all conditions that I checked.

I am also getting a crash when trying to open a DirectSound primary buffer in something I am working on ```( res = directSound->CreateSoundBuffer(&bufferDesc, primaryBuffer.GetAddressOf(), null);  )```, when trying to launch the Release build from the command line . It runs fine from the IDE though...and the Debug version runs from the command line with no problem! Not sure what is going on there. But maybe it is related? Something to do with the dynamic dispatch over a comptr and something gets optimized out in Release mode? Not sure

**Comment by jayrulez** [comment]
The media directory needs to be next to the exe if you're running like that. It will work from the IDE because the IDE will set the working directory to the project directory which has the media dir there. I can update the samples to fail more gracefully.

**Comment by jayrulez** [comment]
I will look at your other issue later. It would help if you post more code for context.

**Comment by wilsonk** [comment]
The ComPtrs are globals, and then the setup code is pretty standard I think. I thought maybe there was some sound card contention, but I turned everything else off and it still fails in the same spot. I am also not playing a sound from a file later on, rather I am generating it, but the code doesn't get that far in Release mode anyways. As stated, it works fine on Debug.

If I remove all the Runtime.Error calls, just to get to the main function, then the DirectSound->Lock function panics...as it should, I suppose.

```
        private static ComPtr<IDirectSound> directSound = default;
	private static ComPtr<IDirectSoundBuffer> primaryBuffer = default;
	private static ComPtr<IDirectSoundBuffer> secondaryBuffer = default;

	static void InitSound(HWND Window, uint32 SamplesPerSecond, uint32 BufferSize)
	{
		HRESULT res;
		DSBUFFERDESC bufferDesc;
		WAVEFORMATEX WaveFormat;

		if (!FAILED(DirectSoundCreate(null, directSound.GetAddressOf(), null)))
		{
			// WAVE_FORMAT_PCM not found so use 0x0001
			WaveFormat.wFormatTag = 0x0001;
			WaveFormat.nChannels = 2;
			WaveFormat.wBitsPerSample = 16;
			WaveFormat.nSamplesPerSec = (uint32)SamplesPerSecond;
			WaveFormat.nBlockAlign = (WaveFormat.nChannels * WaveFormat.wBitsPerSample) / 8;
			WaveFormat.nAvgBytesPerSec = WaveFormat.nSamplesPerSec * WaveFormat.nBlockAlign;
			WaveFormat.cbSize = 0;

			if (!FAILED(res = directSound->SetCooperativeLevel(GetDesktopWindow(), DSSCL_PRIORITY)))
			{
				bufferDesc.dwSize = sizeof(DSBUFFERDESC);
				bufferDesc.dwFlags = DSBCAPS_PRIMARYBUFFER | DSBCAPS_CTRLVOLUME;

				if (!FAILED(res = directSound->CreateSoundBuffer(&bufferDesc, primaryBuffer.GetAddressOf(), null)))
				{
					if (!FAILED(res = primaryBuffer->SetFormat(&WaveFormat)))
					{
					}
					else
					{
						Console.WriteLine("Failed to Set Format for Sound: {}", res);
						Runtime.FatalError();
					}
				}
				else
				{
					Console.WriteLine("Failed to create Primary Sound Buffer: {}", res);
					Runtime.FatalError();
				}
			}
			else
			{
				Console.WriteLine("Couldn't set priority level");
				Runtime.FatalError();
			}
		}
		else
		{
			Console.WriteLine("Couldn't create DirectSound instance");
			Runtime.FatalError();
		}

		DSBUFFERDESC secondaryBufferDesc;
		secondaryBufferDesc.dwSize = sizeof(DSBUFFERDESC);
		secondaryBufferDesc.dwFlags = DSBCAPS_GLOBALFOCUS | DSBCAPS_GETCURRENTPOSITION2;
		secondaryBufferDesc.dwBufferBytes = BufferSize;
		secondaryBufferDesc.lpwfxFormat = &WaveFormat;
		secondaryBufferDesc.guid3DAlgorithm = Guid.Empty;

		if (FAILED(res = directSound->CreateSoundBuffer(&secondaryBufferDesc, secondaryBuffer.GetAddressOf(), null)))
		{
			Console.WriteLine("Failed to create Primary Sound Buffer: {}", res);
			Runtime.FatalError();
		}
	}
```

**Comment by wilsonk** [comment]
Sorry about this...it ends up that I had some sort of weird artifacts left over from a different Win32 binding I was trying and that must be what was causing the crash in Release mode. Apologies for the noise. Seems to work fine now.
